dim: 100
disrupted_version: 2.0
nominal_version: 2.0
ratio: 0.5
samples: 50000
train_test_validation_split:
- 0.5
- 0.4
- 0.1
mean_perturbance: [0.0, 1e-5, 1e-4, 1e-3]
cov_disruption: [1e-1, 1e-2, 1e-3, 1e-4, 0.0]